package main

import (
	"fmt"
)

func main() {
	fmt.Println("# generated by vectors.go - do not edit")
	fmt.Println("# handlers")
	fmt.Println(".globl alltraps")

	for i := 0; i < 256; i++ {
		fmt.Printf(".globl vector%d\n", i)
		fmt.Printf("vector%d:\n", i)
		// Cek apakah interrupt ini memiliki error code bawaan dari x86
		if !(i == 8 || (i >= 10 && i <= 14) || i == 17) {
			fmt.Println("  pushl $0")
		}
		fmt.Printf("  pushl $%d\n", i)
		fmt.Println("  jmp alltraps")
	}

	fmt.Println("\n# vector table")
	fmt.Println(".data")
	fmt.Println(".globl vectors")
	fmt.Println("vectors:")
	for i := 0; i < 256; i++ {
		fmt.Printf("  .long vector%d\n", i)
	}
}
